- hosts: backend
  tasks:
   - package:
       name: httpd
       state: present

   - service:
       name: "httpd"
       state: started
       enabled: yes

   - template:
       src: "IP.html"
       dest: "/var/www/html"
       
   - firewalld: 
       port: "80/tcp"
       state: enabled
       immediate: yes
       permanent: yes     
