- hosts: backend
  become: yes
  tasks:
   - package:
       name: httpd
       state: present

   - service:
       name: "httpd"
       state: started
       enabled: yes

   - template:
       src: "IP.html"
       dest: "/var/www/html"
       
  
