- hosts: "frontend"
  vars:
    - x:
        - 1
        - 2
        - 3
        - 4   
  tasks:
    - name: "Installing load balancer software "
      package: 
        name: "haproxy"
 
        # - name: "configuration of haproxy file "
        # template: 
        #src: "haproxy.cfg"
        # dest: "/etc/haproxy/haproxy.cfg"

    - name: "replace portno in config file"
      replace:
        path: "/etc/haproxy/haproxy.cfg"
        regexp: ":5000"
        replace: ":8080"
    
    - name: "removing line from config file"
      lineinfile:
        path: "/etc/haproxy/haproxy.cfg"
        regexp : "   server  app{{ item }} 127.0.0.1:500{{ item }} check"
        state: absent
      with_items:
        - 1
        - 2
        - 3
        - 4

    - name: "adding backend server"
      blockinfile:
        path: "/etc/haproxy/haproxy.cfg" 
        block: |
                {% for i in groups['backend'] %}
                server app{{ loop.index }} {{ i }}:80 check
                {% endfor %}
      notify: restarting service

    - name: "enabling port 8080"
      firewalld:
        port: "8080/tcp"
        state: enabled
        permanent: yes
        immediate: yes

    - name: starting services
      service:
        name: haproxy
        state: started

       
  handlers:        
    - name: restarting service
      service:
        name: haproxy
        state: restarted

               
